name: wandr-backend
region: nyc
databases:
  - name: db
    engine: PG
    cluster_name: wandr-db
    db_name: defaultdb
    db_user: doadmin
    production: true

services:
  - name: backend
    github:
      repo: IriBr/tourist-attraction-app
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    source_dir: /
    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        value: ${db.DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        value: super-secret-jwt-key-change-in-production-2024
      - key: JWT_REFRESH_SECRET
        scope: RUN_TIME
        value: super-secret-refresh-key-change-in-production-2024
      - key: NODE_ENV
        scope: RUN_TIME
        value: production
      - key: PORT
        scope: RUN_TIME
        value: "3000"
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    health_check:
      http_path: /health
  - name: admin
    github:
      repo: IriBr/tourist-attraction-app
      branch: main
      deploy_on_push: true
    dockerfile_path: admin/Dockerfile
    source_dir: /
    envs:
      - key: VITE_API_URL
        scope: BUILD_TIME
        value: https://wandr-backend-k87hq.ondigitalocean.app/api/v1
    http_port: 8080
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb

ingress:
  rules:
    - match:
        path:
          prefix: /api
      component:
        name: backend
        preserve_path_prefix: true
    - match:
        path:
          prefix: /health
      component:
        name: backend
        preserve_path_prefix: true
    - match:
        path:
          prefix: /
      component:
        name: admin
